### ISSUE TITLE
Allow administrator add/create/update/delete admins

### ISSUE THREAD

**Issue by KhoaNDAHopee** [HopeeRuby/beauty_care#13]
- Add link to Dashboard, Admins on left menu
- Allow admin with role: admin can add/create/update/delete admins (admin with role: customer_service can't see it on left menu)
- Add unit test for CRUD admins
- Admin with role: customer_service access admins page (ex: administrator/admins/new) will redirect to permission denied page
- Implement layout for permission denied page
- Fix bug, only admin with status active can login

### Note:
- Use pundit https://github.com/varvet/pundit
- https://viblo.asia/p/su-dung-gem-pundit-trong-ung-dung-rails-maGK7z6b5j2

**Comment by khoa250200** [comment]
Frontend: (Mr. Ngọc Anh)
1. Add link to Dashboard, Admins on left menu
2. Implement layout for permisstion denied page

Backend: (Khoa & Thắm)
1. Create admins_controller.rb file with CRUD actions
2. Implement action base on admin role
- Use pundit: https://github.com/varvet/pundit
- Documentation: https://viblo.asia/p/su-dung-gem-pundit-trong-ung-dung-rails-maGK7z6b5j2
4. Fix bug, implement login action base on status
