### ISSUE TITLE
Setup admin

### ISSUE THREAD

**Issue by KhoaNDAHopee** [HopeeRuby/beauty_care#4]
- Setup gem https://github.com/heartcombo/devise
- Allow admin login to admin page
- Use this layout for login form https://preview.colorlib.com/theme/bootstrap/login-form-15/
- Admin tables:
  - first_name
  - last_name
  - email
  - password
  - phone
  - status (active, inactive)
  - role: (admin, customer_service) use enum https://viblo.asia/p/su-dung-enum-trong-ruby-on-rails-1l0rvm4oGyqA
 - Update file seed.rb (use faker, factory_bot create sample admin)

**Comment by hongthamnguyen2k** [comment]
- Setup gem https://github.com/heartcombo/devise and - Create Admin tables: (Khoa & anh NAnh)
  + first_name
  + last_name
  + email
  + password
  + phone
  + status (active, inactive)
  + role: (admin, customer_service) use enum https://viblo.asia/p/su-dung-enum-trong-ruby-on-rails-1l0rvm4oGyqA
- Update file seed.rb (use faker, factory_bot create sample admin)
- Use this layout for login form https://preview.colorlib.com/theme/bootstrap/login-form-15/ (Thắm)
